// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/google/uuid"
)

type Message struct {
	ID       uuid.UUID
	Name     string
	ThreadID uuid.UUID
	AuthorID uuid.UUID
}

type Permission struct {
	ID   int64
	Name string
}

type Role struct {
	ID   int64
	Name string
}

type RolesPermission struct {
	RoleID       int64
	PermissionID int64
}

type Section struct {
	ID   uuid.UUID
	Name string
}

type Subsection struct {
	ID        uuid.UUID
	Name      string
	SectionID uuid.UUID
	AuthorID  uuid.UUID
}

type Theme struct {
	ID           uuid.UUID
	Name         string
	SubsectionID uuid.UUID
	AuthorID     uuid.UUID
}

type Thread struct {
	ID       uuid.UUID
	Name     string
	ThemeID  uuid.UUID
	AuthorID uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Email    string
	Password string
	Login    string
	RoleID   int64
	Token    string
}
