// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getRole = `-- name: GetRole :one
SELECT roles.name
FROM users
         JOIN roles ON users.role_id = roles.id
WHERE users.id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
